server:
    port: ${port:8092}

spring:
#thymeleaf:
#???????
#prefix: classpath:/templates/
#suffix: .html
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/fang?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root